<x-app-layout>
    <x-slot name="header"><div><a href="{{ route('offer-journeys.index') }}" class="text-sm font-semibold text-[#647a0b] hover:text-[#854f38]">Pages et campagnes</a><h1 class="mt-1 text-2xl font-semibold text-gray-900">Votre utilisation</h1><p class="mt-1 text-sm text-gray-600">Suivez vos limites mensuelles. Les simulations et les messages de test ne sont jamais comptabilisés.</p></div></x-slot>
    <div class="py-6"><div class="mx-auto max-w-5xl space-y-5 px-4 sm:px-6 lg:px-8">
        <section class="grid gap-4 sm:grid-cols-2" aria-label="Utilisation des parcours d'offre">
            <article class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-gray-600">Parcours actifs</p><p class="mt-2 text-2xl font-semibold text-gray-900">{{ $usage['active'] }} <span class="text-base font-normal text-gray-500">/ {{ $usage['active_limit'] }}</span></p><div class="mt-3 h-2 overflow-hidden rounded-full bg-gray-100"><div class="h-full bg-[#647a0b]" style="width: {{ min(100, $usage['active_limit'] ? ($usage['active'] / $usage['active_limit']) * 100 : 0) }}%"></div></div></article>
            <article class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-gray-600">Messages marketing envoyés ce mois</p><p class="mt-2 text-2xl font-semibold text-gray-900">{{ $usage['emails'] }} <span class="text-base font-normal text-gray-500">/ {{ $usage['email_limit'] }}</span></p><div class="mt-3 h-2 overflow-hidden rounded-full bg-gray-100"><div class="h-full bg-[#854f38]" style="width: {{ min(100, $usage['email_limit'] ? ($usage['emails'] / $usage['email_limit']) * 100 : 0) }}%"></div></div></article>
            <article class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-gray-600">Contacts interesses</p><p class="mt-2 text-2xl font-semibold text-gray-900">{{ $usage['contacts'] }}</p><p class="mt-2 text-sm text-gray-500">Uniquement les contacts de ce module.</p></article>
            <article class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-gray-600">Ressources privées</p><p class="mt-2 text-2xl font-semibold text-gray-900">{{ number_format($usage['storage_bytes'] / 1048576, 1, ',', ' ') }} Mo</p><p class="mt-2 text-sm text-gray-500">{{ $usage['file_count'] }} fichier(s), stocké(s) de manière privée.</p></article>
        </section>
        <p class="rounded-lg border border-[#dfe6c7] bg-[#f7f9ec] px-4 py-3 text-sm text-gray-700">Si une limite est atteinte, seules les nouvelles actions de ce module sont suspendues. Votre agenda, vos rendez-vous, vos clients et vos autres données Olithea restent inchangés.</p>
    </div></div>
</x-app-layout>
