@foreach($blocks as $block)
    @php($data = $block['data'] ?? [])
    @if($block['type'] === 'audience' && filled($data['text'] ?? null))
        <section class="border-y border-[#e5e8dc] bg-[#f7f8f3]"><div class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">À qui s'adresse cette offre ?</h2><p class="mt-3 max-w-3xl leading-7 text-gray-600">{{ $data['text'] }}</p></div></section>
    @elseif($block['type'] === 'outcomes' && !empty($data['items']))
        <section class="bg-white"><div class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">Ce que vous allez obtenir</h2><ul class="mt-5 grid gap-3 sm:grid-cols-2">@foreach($data['items'] as $item)<li class="flex gap-3 border border-gray-200 p-4 text-gray-700"><span class="mt-0.5 text-[#647a0b]" aria-hidden="true">✓</span><span>{{ $item }}</span></li>@endforeach</ul></div></section>
    @elseif($block['type'] === 'steps' && !empty($data['items']))
        <section class="border-y border-[#e5e8dc] bg-[#f7f8f3]"><div class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">Comment cela se déroule</h2><ol class="mt-5 grid gap-4 md:grid-cols-3">@foreach($data['items'] as $item)<li class="border border-gray-200 bg-white p-4"><span class="text-sm font-semibold text-[#854f38]">Étape {{ $loop->iteration }}</span><p class="mt-2 text-gray-700">{{ $item }}</p></li>@endforeach</ol></div></section>
    @elseif($block['type'] === 'gallery' && !empty($data['items']))
        <section class="bg-white"><div class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">En images</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($data['items'] as $item)<figure><img src="{{ $item['url'] }}" alt="{{ $item['alt'] }}" loading="lazy" class="aspect-[4/3] w-full object-cover"><figcaption class="mt-2 text-sm text-gray-600">{{ $item['alt'] }}</figcaption></figure>@endforeach</div></div></section>
    @elseif($block['type'] === 'video' && ($embedUrl = app(\App\Domain\OfferJourneys\Services\OfferJourneyMediaUrl::class)->embed($data['url'] ?? null)))
        <section class="border-y border-[#e5e8dc] bg-[#f7f8f3]"><div class="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">Présentation en vidéo</h2><div class="mt-5 aspect-video overflow-hidden bg-black"><iframe src="{{ $embedUrl }}" title="Présentation vidéo de l'offre" loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen class="h-full w-full"></iframe></div></div></section>
    @elseif($block['type'] === 'testimonials' && !empty($data['items']))
        <section class="bg-white"><div class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">Témoignages</h2><div class="mt-5 grid gap-4 md:grid-cols-2">@foreach($data['items'] as $item)<figure class="border-l-4 border-[#647a0b] bg-[#f7f8f3] p-5"><blockquote class="leading-7 text-gray-700">« {{ $item['quote'] }} »</blockquote><figcaption class="mt-3 text-sm font-semibold text-gray-900">{{ $item['author'] }}</figcaption></figure>@endforeach</div></div></section>
    @elseif($block['type'] === 'speaker' && filled($data['name'] ?? null))
        <section class="border-y border-[#e5e8dc] bg-[#f7f8f3]"><div class="mx-auto flex max-w-4xl flex-col gap-6 px-4 py-10 sm:flex-row sm:items-center sm:px-6 lg:px-8">@if(filled($data['image_url'] ?? null))<img src="{{ $data['image_url'] }}" alt="Portrait de {{ $data['name'] }}" loading="lazy" class="h-32 w-32 shrink-0 object-cover">@endif<div><p class="text-sm font-semibold uppercase text-[#854f38]">Intervenant</p><h2 class="mt-1 text-xl font-semibold text-gray-900">{{ $data['name'] }}</h2>@if(filled($data['title'] ?? null))<p class="mt-1 text-sm font-medium text-[#647a0b]">{{ $data['title'] }}</p>@endif@if(filled($data['bio'] ?? null))<p class="mt-3 leading-7 text-gray-600">{{ $data['bio'] }}</p>@endif</div></div></section>
    @elseif($block['type'] === 'price' && filled($data['label'] ?? null))
        <section class="bg-white"><div class="mx-auto max-w-6xl px-4 py-8 text-center sm:px-6 lg:px-8"><p class="text-sm text-gray-500">Tarif</p><p class="mt-1 text-2xl font-semibold text-gray-900">{{ $data['label'] }}</p></div></section>
    @elseif($block['type'] === 'practical' && filled($data['text'] ?? null))
        <section class="bg-white"><div class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">Informations pratiques</h2><p class="mt-3 max-w-3xl whitespace-pre-line leading-7 text-gray-600">{{ $data['text'] }}</p></div></section>
    @elseif($block['type'] === 'faq' && !empty($data['items']))
        <section class="border-t border-[#e5e8dc] bg-[#f7f8f3]"><div class="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8"><h2 class="text-xl font-semibold text-gray-900">Questions fréquentes</h2><div class="mt-5 divide-y divide-gray-200 border border-gray-200 bg-white">@foreach($data['items'] as $item)<details class="p-4"><summary class="cursor-pointer font-medium text-gray-900">{{ $item['question'] ?? '' }}</summary><p class="mt-3 leading-6 text-gray-600">{{ $item['answer'] ?? '' }}</p></details>@endforeach</div></div></section>
    @endif
@endforeach
