<x-app-layout>
    <x-slot name="header"><div><a href="{{ route('offer-journeys.contacts.index') }}" class="text-sm font-medium text-[#647a0b]">Personnes intéressées</a><h1 class="mt-1 text-2xl font-semibold text-gray-900">Importer des contacts</h1><p class="mt-1 text-sm text-gray-500">Contrôlez chaque ligne avant de créer les fiches. Aucun message ne part pendant l’import.</p></div></x-slot>
    <div class="py-6"><div class="mx-auto grid max-w-6xl gap-5 px-4 sm:px-6 lg:grid-cols-[360px_minmax(0,1fr)] lg:px-8">
        <aside class="space-y-5"><section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Créer un aperçu</h2><p class="mt-1 text-xs text-gray-500">CSV de 2 Mo maximum, 2 000 lignes. Colonne obligatoire: <code>email</code>. Colonnes facultatives: <code>prenom</code>, <code>nom</code>, <code>telephone</code>, <code>consentement_marketing</code>.</p><form method="POST" action="{{ route('offer-journeys.contacts.import.preview') }}" enctype="multipart/form-data" class="mt-4 space-y-4">@csrf
            <div><label class="block text-sm font-medium text-gray-700" for="csv-file">Fichier CSV</label><input id="csv-file" type="file" name="file" accept=".csv,text/csv" required class="mt-1 block w-full text-sm"></div>
            <div><label class="block text-sm font-medium text-gray-700" for="consent-proof">Preuve de consentement</label><input id="consent-proof" name="consent_proof" value="{{ old('consent_proof') }}" maxlength="255" class="mt-1 block w-full rounded-md border-gray-300 text-sm" placeholder="Ex. formulaire signé le 10/07/2026"><p class="mt-1 text-xs text-gray-500">Obligatoire si une ligne autorise les relances marketing.</p></div>
            <button class="w-full rounded-md bg-[#647a0b] px-4 py-2 text-sm font-semibold text-white">Analyser le fichier</button>
        </form></section></aside>

        <div class="space-y-5">
            @if(session('success'))<div class="rounded-md border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
            @if($errors->any())<div class="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
            @php($selected = request('import') ? $imports->firstWhere('id', (int) request('import')) : null)
            @if($selected)
                <section class="rounded-lg border border-[#dfe6c7] bg-white p-5 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="font-semibold text-gray-900">Aperçu: {{ $selected->original_filename }}</h2><p class="mt-1 text-sm text-gray-500">{{ data_get($selected->report_json, 'valid', 0) }} ligne(s) prête(s), {{ count(data_get($selected->report_json, 'ignored', [])) }} ignorée(s).</p></div><span class="rounded-full bg-[#f0f4df] px-2 py-0.5 text-xs font-medium text-[#526509]">Aucun envoi</span></div>
                    <div class="mt-4 max-h-72 overflow-auto rounded-md border border-gray-200"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="sticky top-0 bg-gray-50"><tr><th class="px-3 py-2 text-left">Email</th><th class="px-3 py-2 text-left">Nom</th><th class="px-3 py-2 text-left">Relances</th></tr></thead><tbody class="divide-y divide-gray-100">@foreach(array_slice($selected->rows_json, 0, 100) as $row)<tr><td class="px-3 py-2">{{ $row['email'] }}</td><td class="px-3 py-2">{{ trim($row['first_name'].' '.$row['last_name']) ?: '—' }}</td><td class="px-3 py-2">{{ $row['marketing_consent'] ? 'Oui, avec preuve' : 'Non' }}</td></tr>@endforeach</tbody></table></div>
                    @if($selected->status === 'preview')<form method="POST" action="{{ route('offer-journeys.contacts.import.commit', $selected) }}" class="mt-4" onsubmit="return confirm('Créer ces contacts sans envoyer de message ?')">@csrf<button class="rounded-md bg-[#647a0b] px-4 py-2 text-sm font-semibold text-white">Confirmer l’import</button></form>@endif
                </section>
            @endif
            <section class="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-200 px-5 py-4"><h2 class="font-semibold text-gray-900">Imports récents</h2></div><div class="divide-y divide-gray-100">@forelse($imports as $import)<div class="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><a href="{{ route('offer-journeys.contacts.import.index', ['import' => $import->id]) }}" class="font-medium text-gray-900 hover:text-[#647a0b]">{{ $import->original_filename }}</a><p class="mt-1 text-xs text-gray-500">{{ $import->created_at->format('d/m/Y H:i') }} · {{ data_get($import->report_json, 'valid', 0) }} ligne(s) valides</p></div><div class="flex items-center gap-3"><span class="text-xs text-gray-600">{{ ['preview'=>'À confirmer','committed'=>'Importé','rolled_back'=>'Annulé'][$import->status] ?? $import->status }}</span>@if($import->status === 'committed')<form method="POST" action="{{ route('offer-journeys.contacts.import.rollback', $import) }}" onsubmit="return confirm('Annuler cet import ? Cette action est refusée si un message a déjà été envoyé.')">@csrf<button class="text-xs font-semibold text-red-700">Annuler avant envoi</button></form>@endif</div></div>@empty<div class="px-5 py-10 text-center text-sm text-gray-500">Aucun import.</div>@endforelse</div></section>
        </div>
    </div></div>
</x-app-layout>
