<x-app-layout>
    <x-slot name="header"><div><a href="{{ route('offer-journeys.contacts.index') }}" class="text-sm font-medium text-[#647a0b] hover:text-[#854f38]">Personnes intéressées</a><h1 class="mt-1 text-2xl font-semibold text-gray-900">Groupes et étiquettes</h1></div></x-slot>
    <div class="py-6"><div class="mx-auto grid max-w-7xl gap-5 px-4 sm:px-6 lg:grid-cols-[minmax(0,1fr)_360px] lg:px-8">
        <div class="space-y-5">
            @if(session('success'))<div class="rounded-md border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
            <section class="rounded-lg border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-200 px-5 py-4"><h2 class="font-semibold text-gray-900">Segments dynamiques</h2><p class="mt-1 text-sm text-gray-500">Les contacts sont recalculés automatiquement à l'ouverture.</p></div>@forelse($segments as $segment)<div class="flex items-center justify-between gap-4 border-b border-gray-100 px-5 py-4 last:border-0"><div><a href="{{ route('offer-journeys.contacts.index', ['segment_id'=>$segment->id]) }}" class="font-medium text-gray-900 hover:text-[#647a0b]">{{ $segment->name }}</a><p class="mt-1 text-sm text-gray-500">{{ $segment->contacts_count }} contact(s) · {{ $segment->description ?: 'Règle enregistrée' }}</p></div><form method="POST" action="{{ route('offer-journeys.contacts.segments.destroy', $segment) }}">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-700">Supprimer</button></form></div>@empty<p class="px-5 py-8 text-sm text-gray-500">Aucun segment pour le moment.</p>@endforelse</section>
        </div>
        <aside class="space-y-5">
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Créer un segment</h2><form method="POST" action="{{ route('offer-journeys.contacts.segments.store') }}" class="mt-4 space-y-3" x-data="{ field: 'status' }">@csrf<input name="name" required maxlength="120" placeholder="Nom du segment" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"><textarea name="description" rows="2" maxlength="500" placeholder="Description facultative" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"></textarea><select name="field" x-model="field" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"><option value="status">Statut du contact</option><option value="tag">Étiquette</option><option value="journey">Parcours</option><option value="inactive_days">Inactif depuis</option><option value="marketing_consent">Consentement marketing</option></select><select x-show="field === 'status'" :disabled="field !== 'status'" name="value" class="block w-full rounded-md border-gray-300 text-sm"><option value="new">Nouveau</option><option value="qualifying">À qualifier</option><option value="contacted">Échange en cours</option><option value="converted">Converti</option><option value="not_now">Pas maintenant</option></select><select x-show="field === 'tag'" :disabled="field !== 'tag'" name="value" class="block w-full rounded-md border-gray-300 text-sm">@foreach($tags as $tag)<option value="{{ $tag->id }}">{{ $tag->name }}</option>@endforeach</select><select x-show="field === 'journey'" :disabled="field !== 'journey'" name="value" class="block w-full rounded-md border-gray-300 text-sm">@foreach($journeys as $journey)<option value="{{ $journey->id }}">{{ $journey->name }}</option>@endforeach</select><input x-show="field === 'inactive_days'" :disabled="field !== 'inactive_days'" type="number" min="1" max="3650" name="value" value="30" class="block w-full rounded-md border-gray-300 text-sm"><input :disabled="field !== 'marketing_consent'" type="hidden" name="value" value="1"><button class="w-full rounded-md bg-[#647a0b] px-3 py-2 text-sm font-semibold text-white hover:bg-[#526509]">Créer le segment</button></form></section>
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Nouvelle étiquette</h2><form method="POST" action="{{ route('offer-journeys.contacts.tags.store') }}" class="mt-4 flex gap-2">@csrf<input name="name" required maxlength="80" placeholder="Ex. atelier juillet" class="min-w-0 flex-1 rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"><button class="rounded-md border border-[#647a0b] px-3 py-2 text-sm font-semibold text-[#647a0b]">Ajouter</button></form><div class="mt-4 flex flex-wrap gap-2">@foreach($tags as $tag)<span class="rounded-full bg-[#f0f4df] px-2.5 py-1 text-xs font-medium text-[#526509]">{{ $tag->name }}</span>@endforeach</div></section>
        </aside>
    </div></div>
</x-app-layout>
