<x-app-layout>
    <x-slot name="header"><div><a href="{{ route('offer-journeys.contacts.index') }}" class="text-sm font-medium text-[#647a0b] hover:text-[#854f38]">Personnes intéressées</a><h1 class="mt-1 text-2xl font-semibold text-gray-900">{{ $contact->display_name }}</h1><p class="mt-1 text-sm text-gray-500">{{ $contact->email }} @if($contact->phone)· {{ $contact->phone }}@endif</p></div></x-slot>
    <div class="py-6"><div class="mx-auto grid max-w-7xl gap-5 px-4 sm:px-6 lg:grid-cols-[minmax(0,1fr)_340px] lg:px-8">
        <div class="space-y-5">
            @if(session('success'))<div class="rounded-md border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
            @if($nextActionRecommendation)
                <section class="rounded-lg border border-[#dfe6c7] bg-[#f7f9ec] p-4">
                    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                        <div><p class="text-xs font-semibold uppercase text-[#526509]">Prochaine action recommandée</p><p class="mt-1 text-sm font-medium text-gray-900">{{ $nextActionRecommendation }}</p></div>
                        <div class="flex flex-wrap gap-2">
                            <a href="mailto:{{ $contact->email }}" class="inline-flex items-center justify-center rounded-md bg-[#647a0b] px-3 py-2 text-sm font-semibold text-white hover:bg-[#526509]">Envoyer un email</a>
                            @if($contact->phone)<a href="tel:{{ preg_replace('/[^0-9+]/', '', $contact->phone) }}" class="inline-flex items-center justify-center rounded-md border border-[#647a0b] bg-white px-3 py-2 text-sm font-semibold text-[#526509] hover:bg-[#f7f9ec]">Appeler</a>@endif
                        </div>
                    </div>
                </section>
            @endif
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Parcours et activité</h2><div class="mt-4 space-y-4">@forelse($contact->activities as $activity)<div class="border-l-2 border-[#cbd5a5] pl-4"><p class="text-sm font-medium text-gray-900">{{ $activity->title }}</p>@if(($activity->metadata['note'] ?? null) && $activity->type === 'internal_note')<p class="mt-1 whitespace-pre-line text-sm text-gray-600">{{ $activity->metadata['note'] }}</p>@endif<p class="mt-1 text-xs text-gray-500">{{ $activity->occurred_at->format('d/m/Y H:i') }}</p></div>@empty<p class="text-sm text-gray-500">Aucune activité enregistrée.</p>@endforelse</div></section>
            @if($contact->messageDeliveries->isNotEmpty())<section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Messages</h2><div class="mt-4 divide-y divide-gray-100">@foreach($contact->messageDeliveries as $delivery)<div class="flex items-start justify-between gap-4 py-3 text-sm"><div><p class="font-medium text-gray-900">{{ $delivery->subject }}</p><p class="mt-1 text-xs text-gray-500">{{ $delivery->sent_at?->format('d/m/Y H:i') ?? (['queued'=>'En attente','sending'=>'En cours','sent'=>'Envoyé','failed'=>'Échec','skipped'=>'Non envoyé'][$delivery->status] ?? $delivery->status) }}</p></div><span class="text-xs font-medium text-gray-500">{{ $delivery->category === 'transactional' ? 'Message demandé' : 'Relance facultative' }}</span></div>@endforeach</div></section>@endif
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Origine</h2><div class="mt-4 divide-y divide-gray-100">@foreach($contact->entries as $entry)<div class="py-3"><a href="{{ route('offer-journeys.show', $entry->journey) }}" class="font-medium text-[#647a0b] hover:text-[#854f38]">{{ $entry->journey->name }}</a><p class="mt-1 text-sm text-gray-500">{{ $entry->first_utm_source ?: 'Accès direct' }} · entrée le {{ $entry->entered_at->format('d/m/Y') }}</p></div>@endforeach</div></section>
            @if($relatedBusiness->isNotEmpty())<section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Rendez-vous, achats et inscriptions</h2><p class="mt-1 text-xs text-gray-500">Vue commerciale uniquement. Les notes de consultation et informations cliniques ne sont pas affichées ici.</p><div class="mt-4 divide-y divide-gray-100">@foreach($relatedBusiness->sortByDesc('date') as $item)<div class="flex items-start justify-between gap-4 py-3"><div><p class="text-sm font-medium text-gray-900">{{ $item['label'] }}</p><p class="mt-1 text-xs text-gray-500">{{ $item['type'] }} · {{ $item['date']?->format('d/m/Y H:i') }}</p></div><span class="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">{{ $item['status'] ?: '—' }}</span></div>@endforeach</div></section>@endif
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Consentements</h2><div class="mt-4 space-y-3">@foreach($contact->consents as $consent)<div class="flex items-start justify-between gap-4 text-sm"><div><p class="font-medium text-gray-900">{{ ['request_processing'=>'Traitement de la demande','requested_response'=>'Réponse à la demande','marketing_follow_up'=>'Suivis liés à cette offre'][$consent->purpose] ?? 'Utilisation autorisée des coordonnées' }}</p><p class="mt-1 text-xs text-gray-500">Version {{ $consent->text_version }} · {{ $consent->granted_at?->format('d/m/Y H:i') }}</p></div><span class="rounded-full px-2 py-0.5 text-xs font-medium {{ $consent->status === 'granted' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-600' }}">{{ ['granted'=>'Accordé','withdrawn'=>'Retiré','expired'=>'Expiré'][$consent->status] ?? $consent->status }}</span></div>@endforeach</div></section>
        </div>
        <aside class="space-y-5">
            @if(config('offer_journeys.client_tags_enabled') && $contact->clientProfile?->marketingTags?->isNotEmpty())
                <section class="rounded-lg border border-[#dfe6c7] bg-[#f7f9ec] p-5">
                    <h2 class="font-semibold text-gray-900">Repères de la fiche client</h2>
                    <div class="mt-3 flex flex-wrap gap-2">
                        @foreach($contact->clientProfile->marketingTags as $tag)
                            <span class="rounded-full border border-[#dfe6c7] bg-white px-2.5 py-1 text-xs font-medium text-[#526509]">{{ $tag->name }}</span>
                        @endforeach
                    </div>
                    <form method="POST" action="{{ route('offer-journeys.client-tags.attach', $contact->clientProfile) }}" class="mt-3 flex gap-2">
                        @csrf
                        <label for="linked-client-tag" class="sr-only">Ajouter un repère à la fiche client</label>
                        <select id="linked-client-tag" name="tag_id" required class="min-w-0 flex-1 rounded-md border-gray-300 text-xs">
                            <option value="">Ajouter un repère</option>
                            @foreach($availableTags->whereNotIn('id', $contact->clientProfile->marketingTags->pluck('id')) as $tag)<option value="{{ $tag->id }}">{{ $tag->name }}</option>@endforeach
                        </select>
                        <button class="rounded-md border border-[#647a0b] px-2.5 py-1.5 text-xs font-semibold text-[#647a0b]">Ajouter</button>
                    </form>
                    <p class="mt-3 text-xs text-gray-600">Ces étiquettes sont utilisées par les segments sans être copiées sur ce contact. Elles ne valent pas consentement marketing.</p>
                    <a href="{{ route('client_profiles.show', $contact->clientProfile) }}" class="mt-3 inline-flex text-xs font-semibold text-[#647a0b]">Ouvrir la fiche client</a>
                </section>
            @endif
            @if($duplicateSuggestions->isNotEmpty())<section class="rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 class="font-semibold text-amber-950">Doublon possible</h2><p class="mt-1 text-xs text-amber-900">Vérifiez l’identité avant de fusionner. Aucun dossier client n’est supprimé.</p><div class="mt-3 space-y-3">@foreach($duplicateSuggestions as $duplicate)<div class="rounded-md border border-amber-200 bg-white p-3"><p class="text-sm font-medium text-gray-900">{{ $duplicate->display_name }}</p><p class="text-xs text-gray-500">{{ $duplicate->email }} @if($duplicate->phone)· {{ $duplicate->phone }}@endif</p><form method="POST" action="{{ route('offer-journeys.contacts.merge', $contact) }}" class="mt-2" onsubmit="return confirm('Fusionner ces deux fiches marketing ?')">@csrf<input type="hidden" name="duplicate_id" value="{{ $duplicate->id }}"><button class="text-xs font-semibold text-amber-800">Fusionner après vérification</button></form></div>@endforeach</div></section>@endif
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Étiquettes</h2><div class="mt-3 flex flex-wrap gap-2">@forelse($contact->tags as $tag)<form method="POST" action="{{ route('offer-journeys.contacts.tags.detach', [$contact, $tag]) }}">@csrf @method('DELETE')<button class="rounded-full bg-[#f0f4df] px-2.5 py-1 text-xs font-medium text-[#526509]" title="Retirer l'étiquette">{{ $tag->name }} ×</button></form>@empty<span class="text-sm text-gray-500">Aucune étiquette</span>@endforelse</div><form method="POST" action="{{ route('offer-journeys.contacts.tags.attach', $contact) }}" class="mt-4 flex gap-2">@csrf<label for="tag_id" class="sr-only">Ajouter une étiquette</label><select id="tag_id" name="tag_id" class="min-w-0 flex-1 rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]">@foreach($availableTags as $tag)<option value="{{ $tag->id }}">{{ $tag->name }}</option>@endforeach</select><button class="rounded-md border border-[#647a0b] px-3 py-2 text-sm font-semibold text-[#647a0b]" @disabled($availableTags->isEmpty())>Ajouter</button></form></section>
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Suivi</h2><form method="POST" action="{{ route('offer-journeys.contacts.pipeline.move', $contact) }}" class="mt-4">@csrf @method('PUT')<label for="pipeline_stage_id" class="block text-sm font-medium text-gray-700">Étape de suivi</label><select id="pipeline_stage_id" name="pipeline_stage_id" class="mt-1 block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]">@foreach($stages as $stage)<option value="{{ $stage->id }}" @selected($contact->pipeline_stage_id===$stage->id)>{{ $stage->name }}</option>@endforeach</select><button class="mt-3 w-full rounded-md bg-[#647a0b] px-3 py-2 text-sm font-semibold text-white hover:bg-[#526509]">Mettre à jour</button></form></section>
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Nouvelle tâche</h2><form method="POST" action="{{ route('offer-journeys.contacts.tasks.store', $contact) }}" class="mt-4 space-y-3">@csrf<input name="title" required placeholder="Ex. proposer un créneau" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"><input type="datetime-local" name="due_at" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"><select name="priority" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"><option value="normal">Priorité normale</option><option value="high">Prioritaire</option><option value="low">À l'occasion</option></select><textarea name="note" rows="2" placeholder="Note non médicale" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"></textarea><button class="w-full rounded-md border border-[#647a0b] px-3 py-2 text-sm font-semibold text-[#647a0b] hover:bg-[#f7f9ec]">Ajouter la tâche</button></form></section>
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Note interne</h2><p class="mt-1 text-xs text-gray-500">N'ajoutez pas d'information clinique dans cette fiche marketing.</p><form method="POST" action="{{ route('offer-journeys.contacts.notes.store', $contact) }}" class="mt-3 space-y-3">@csrf<textarea name="note" rows="3" required maxlength="2000" class="block w-full rounded-md border-gray-300 text-sm focus:border-[#647a0b] focus:ring-[#647a0b]"></textarea><button class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm font-semibold text-gray-700">Ajouter la note</button></form></section>
            @if($contact->tasks->isNotEmpty())<section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">Tâches</h2><div class="mt-3 space-y-3">@foreach($contact->tasks as $task)<div class="rounded-md border border-gray-200 p-3"><p class="text-sm font-medium text-gray-900">{{ $task->title }}</p><p class="mt-1 text-xs text-gray-500">{{ $task->due_at?->format('d/m/Y H:i') ?? 'Sans échéance' }}</p>@if($task->status === 'open')<form method="POST" action="{{ route('offer-journeys.contacts.tasks.update', [$contact, $task]) }}" class="mt-2">@csrf @method('PUT')<input type="hidden" name="status" value="completed"><button class="text-xs font-semibold text-[#647a0b]">Marquer terminée</button></form>@endif</div>@endforeach</div></section>@endif
            <section class="rounded-lg border border-red-200 bg-white p-5"><h2 class="font-semibold text-gray-900">Données du contact</h2><p class="mt-1 text-sm text-gray-500">L'anonymisation ne modifie aucun rendez-vous, dossier client, facture ou achat existant.</p><form method="POST" action="{{ route('offer-journeys.contacts.anonymize', $contact) }}" class="mt-4" onsubmit="return confirm('Anonymiser définitivement ce contact marketing ?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-700 hover:text-red-900">Anonymiser ce contact</button></form></section>
        </aside>
    </div></div>
</x-app-layout>
