name: Deploy to Server

on:
  push:
    branches:
      - master  # Triggefr this workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest code via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.16.13.99 << 'EOF'
           cd /var/www/project-aromadb && sudo git pull origin master
          EOF
      - name: Update specific tables for data
        run: |
           ssh -o StrictHostKeyChecking=no ubuntu@16.16.13.99 << 'EOF'
            sudo mysql -u root yourdatabase -e "DROP TABLE IF EXISTS recettes, huile_hes, huile_hvs, tisanes;"
            cd /var/www/project-aromadb
            sudo php artisan migrate
            sudo php artisan migrate:refresh --path=/database/migrations/2024_09_02_172024_create_huile_h_e_s_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2024_09_03_093220_create_recettes_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2024_09_05_104212_create_huile_h_v_s_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2024_09_08_103726_create_tisanes_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2024_09_18_151847_create_blog_posts_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2025_03_03_115223_create_trainings_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2025_03_03_115224_create_chapters_table.php
            sudo php artisan migrate:refresh --path=/database/migrations/2025_03_03_115224_create_lessons_table.php
           
            sudo php artisan db:seed --class=RecetteSeeder
            sudo php artisan db:seed --class=HuileHESeeder
            sudo php artisan db:seed --class=HuileHVSeeder
            sudo php artisan db:seed --class=TisaneSeeder
            sudo php artisan db:seed --class=BlogPostSeeder
            sudo php artisan db:seed --class=TrainingSeeder
            sudo php artisan db:seed --class=ChapterSeeder
            sudo php artisan db:seed --class=LessonSeeder
            sudo php artisan sitemap:generate
           EOF
